services:
  traefik:
    build:
      context: .
      dockerfile: Dockerfile
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - "--configFile=/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./acme.json:/acme.json:rw
      - ./dynamic:/dynamic:ro
      - ./traefik.log:/traefik.log:rw
      - ./traefik.yml:/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro