entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    redirect-router:
      rule: "HostRegexp(`{any:.+}`)"
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: noop

  services:
    noop:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1"

api:
  dashboard: true
  insecure: false

log:
  level: INFO
  filePath: /logs/traefik.log

providers:
  file:
    directory: /dynamic
    watch: true

certificatesResolvers:
  stepCA:
    acme:
      caServer: "https://ca.mol.lan/acme/acme/directory"
      email: "sumon@mol.la"
      storage: "acme.json"
      keyType: EC256
      httpChallenge:
        entryPoint: web
